server:
  port: 8085

spring:
  application:
    name: track-calories
  datasource:
    url: jdbc:postgresql://localhost:5432/calories_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#        type: trace
#logging:
#  level:
#    org.hibernate: trace
#    org.hibernate.SQL: trace
#    org.hibernate.orm.jdbc.bind: trace
#    root: trace